### ISSUE TITLE
JDBC.jl fails to retrieve Floating point and BigInt datatypes from Oracle

### ISSUE THREAD

**Issue by bmharsha** [JuliaDB/JDBC.jl#13]
#### Setup

OS = Windows 2008 R2 server SP1
Oracle version = Oracle Database Express Edition 11g Release 2
JDK and JRE version = 1.8.0_65
Table is being created using following query  
``` 
 CREATE TABLE Employee(ID INT, Name VARCHAR(4000), Salary FLOAT, LastLogin DATE, OfficeNo NUMBER(4), JobType VARCHAR2(20) CHECK( JobType IN ('HR', 'Management', 'Accounts')), h NUMBER(8), n NUMBER(11), z NUMBER(20), z1 FLOAT(25), z2 FLOAT(25), cha CHAR, empno NUMBER(6)) 
```
I've created an index on this table 
```
create unique index id_idx on Employee(ID)
```
I inserted 10 records onto this table and all the columns had appropriate values (all of them had Non zero values), when I retrieved this table as a DataFrame , all the values in following columns ```Salary , Z, Z1, Z2``` were zero.

**Comment by bmharsha** [comment]
I used following as a workaround but the original issue still remains

```
      rs = executeQuery(stmt, "select * from Employee")
      JDBC_retrieved = readtable(rs)      
      rs = executeQuery(stmt, "select * from Employee")      #Cannot reiterate through a cursor
      i=1
      for r in rs
         JDBC_retrieved[:Z2][i] = getFloat(r,"z2")
         JDBC_retrieved[:Z][i] = getFloat(r,"z")
         JDBC_retrieved[:Z1][i] = getFloat(r,"z1")
         JDBC_retrieved[:SALARY][i] = getFloat(r,"Salary")
         i=i+1
      end
```

**Comment by aviks** [comment]
So you mean `getFloat(r, "z2")` get's the correct value, but converting it to a DataFrame using `readtable` does not?

**Comment by bmharsha** [comment]
>  So you mean getFloat(r, "z2") get's the correct value, but converting it to a DataFrame using readtable does not?

Correct, getFloat() gets the correct value whereas readtable doesn't.

**Comment by aviks** [comment]
The issue is probably here: https://github.com/JuliaDB/JDBC.jl/blob/master/src/JDBC.jl#L181

Can you do show me the result of `getTableMetaData(rs)`  when you get a chance?
