### ISSUE TITLE
Strange Appveyor error 

### ISSUE THREAD

**Issue by aviks** [JuliaDB/JDBC.jl#14]
Appveyor builds for JDBC are failing with a "No runtests.jl" error, which is clearly inaccurate. 

@tkelman any insights please?

**Comment by aviks** [comment]
https://ci.appveyor.com/project/aviks/jdbc-jl

**Comment by tkelman** [comment]
copy paste error in the Pkg.clone call, second arg should be JDBC not JavaCall

**Comment by aviks** [comment]
Duh! Thanks, and sorry to waste your time.
