### ISSUE TITLE
Unable to Convert JDBC Result Set to DataFrame

### ISSUE THREAD

**Issue by PrinceFlorizel** [JuliaDB/JDBC.jl#30]
As of DataFrames v0.11, I get the following error when trying to turn the result from running an SQL query with JDBC into a DataFrame:

`julia> df = readtable(executeQuery(stmt, "select * from SOME_TABLE"));

UndefVarError: DataArrays not defined

Stacktrace:
 [1] readtable(::JavaCall.JavaObject{Symbol("java.sql.ResultSet")}) at /home/thedude/.julia/v0.6/JDBC/src/JDBC.jl:492`

My workaround for the time being is to use RCall and let R handle the database connection and the data pulls, but it would be great to get this functionality directly in Julia again.

**Comment by aviks** [comment]
Yeah, this package has not been updated to work with the new DataFrames. Needs to be done.

**Comment by aviks** [comment]
This should now be fixed with JDBC.jl v0.2.1 that was released a couple of days back.
